In [ ]:
#numpy

In [2]:
!pip install numpy

In [4]:
!pip install numpy --upgrade

Requirement already up-to-date: numpy in c:\users\toshiba\anaconda3\lib\site-packages (1.18.3)


In [5]:
import numpy as np

In [7]:
array_one = np.array([1,2,3,4,5,6])

array_one

array([1, 2, 3, 4, 5, 6])

In [9]:
numbers = [3,4,5,6,7,8,9]

array_two = np.array(numbers)

array_two

array([3, 4, 5, 6, 7, 8, 9])

In [10]:
type(array_two)

numpy.ndarray

In [11]:
#array of zeros i.e to intialize the array with zero

array_of_zeros = np.zeros((4,5))

array_of_zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
array_of_zeros = np.zeros((4,5),dtype=np.int16)   #dtype=np.int16 removes the dot(.)

array_of_zeros

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int16)

In [14]:
#array internally takes float that's why dot (.) appears in the output

In [16]:
#array of ones i.e initializing array with one

array_of_ones = np.ones((5,5))

array_of_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
array_of_ones = np.ones((5,5),dtype=np.int16)

array_of_ones

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [18]:
#initializing array with any particular number

array_of_numbers = np.full((5,5),2)

array_of_numbers

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])