In [ ]:
#Numpy continued

In [ ]:
#Handling decimalin array

In [1]:
import numpy as np

In [4]:
array_float = np.arange(0,6,0.5)

array_float

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

In [5]:
#Two dimensional array

array_2d = np.array([(5,6,7),(1,2,3)])

array_2d

array([[5, 6, 7],
       [1, 2, 3]])

In [6]:
#nd array

array_nd = np.arange(6).reshape(2,3)

array_nd

array([[0, 1, 2],
       [3, 4, 5]])

In [8]:
#nd array----use of reshape

array_nd1 = np.arange(6).reshape(3,2)   #multiplication of reshape parameter should be equal to range parameter i.e 3*2 = 6

array_nd1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [9]:
#nd array

array_nd2 = np.arange(6).reshape(4,2)  #multiplication of reshape parameter should be equal to range parameter i.e 

array_nd2

ValueError: cannot reshape array of size 6 into shape (4,2)

In [10]:
#printing a 3D array

array_3d = np.arange(24).reshape(4,3,2)

array_3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [11]:
array_3d = np.arange(24).reshape(2,3,4)

array_3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])