In [ ]:
#Arithmatic operation of numpy

In [1]:
import numpy as np

In [3]:
a = np.array([10,10,10])

a

array([10, 10, 10])

In [4]:
b = np.array([5,5,5])

b

array([5, 5, 5])

In [5]:
#adding

a + b

array([15, 15, 15])

In [6]:
#substraction
a - b

array([5, 5, 5])

In [7]:
#substraction
b - a

array([-5, -5, -5])

In [8]:
#multiplication
a * b

array([50, 50, 50])

In [9]:
#division
a/b

array([2., 2., 2.])

In [10]:
#division
b/a

array([0.5, 0.5, 0.5])

In [11]:
#modulus
a % b 

array([0, 0, 0], dtype=int32)

In [12]:
#logical operator

a > 5

array([ True,  True,  True])

In [13]:
a<15

array([ True,  True,  True])

In [14]:
a<5

array([False, False, False])

In [23]:
a = np.array([10,10,10])

a

array([10, 10, 10])

In [24]:
#modifying exicting array rather than creating new one

a *= 3



In [25]:
a

array([30, 30, 30])

In [26]:
b +=a

In [27]:
b

array([35, 35, 35])

In [29]:
a = np.array([10,10,10])

a

array([10, 10, 10])

In [30]:
a**2

array([100, 100, 100], dtype=int32)

In [31]:
a**3

array([1000, 1000, 1000], dtype=int32)

In [32]:
#unary operator

ages = np.array([35,45,98,76,95,52,81])

ages

array([35, 45, 98, 76, 95, 52, 81])

In [33]:
ages.sum()

482

In [34]:
ages.min()

35

In [35]:
ages.max()

98

In [39]:
#in a 2-D array, axis = 0 represents column
#                axis = 1 reprents row

numbers = np.arange(12).reshape(3,4)

numbers

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
numbers.sum(axis=0)   #adding each column

array([12, 15, 18, 21])

In [41]:
numbers.sum(axis=1)  #adding each row

array([ 6, 22, 38])

In [43]:
#Introduction to statistical functions

score = np.array([23.5,69.5,45.1,23.89,32.15,25.95,47.65])

score

array([23.5 , 69.5 , 45.1 , 23.89, 32.15, 25.95, 47.65])

In [50]:
#find mean score

mean = np.mean(score)

mean

38.24857142857143

In [46]:
print(np.mean(score))

38.24857142857143


In [47]:
#find mean score

median = np.median(score)

median

32.15