In [ ]:
#Numpy concept

In [1]:
import numpy as np

In [8]:
n1 =np.array([10,20,30])

n1

array([10, 20, 30])

In [9]:
n2 =np.array([[10,20,30],[40,50,60]])

n2

array([[10, 20, 30],
       [40, 50, 60]])

In [10]:
type(n2)

numpy.ndarray

In [15]:
#intializing numpy with zero

n1 = np.zeros((1,2))

n1


array([[0., 0.]])

In [16]:
n2 = np.zeros((5,5))
n2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
#intializing numpy with number of your choice

n1 = np.full((5,5),11)

n1

array([[11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11]])

In [19]:
#initializing numpy with a range

n1 = np.arange(1,15)
n1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
n1 = np.arange(100,500,50)
n1

array([100, 150, 200, 250, 300, 350, 400, 450])

In [22]:
#Initializing numpy with random number

import random

n1 = np.random.randint(1,50,5)
n1

array([28, 19,  7, 32, 31])

In [24]:
#Checking shape of a numpy array

n2 =np.array([[10,20,30],[40,50,60]])

n2.shape

(2, 3)

In [26]:
n2.shape = (3,2)

n2

array([[10, 20],
       [30, 40],
       [50, 60]])

In [33]:
#Addition of two Numpy array

n1 = np.array([10,20,30])
n2 = np.array([40,50,60])

np.sum([n1,n2])

210

In [28]:
n1 = np.array([10,20,30])   #elemts at same index are added
n2 = np.array([40,50,60])

np.sum([n1,n2],axis=0)

array([50, 70, 90])

In [31]:
n1 = np.array([10,20,30]) #row wise addition
n2 = np.array([40,50,60])

np.sum([n1,n2],axis=1)

array([ 60, 150])

In [36]:
#Joing arrays

#vertical joining

n1 = np.array([10,20,30])
n2 = np.array([40,50,60])

np.vstack((n1,n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [37]:
#horizontal joining

n1 = np.array([10,20,30])
n2 = np.array([40,50,60])

np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

In [38]:
#column-wise joining

n1 = np.array([10,20,30])
n2 = np.array([40,50,60])

np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])